#!/usr/bin/env python

import os
from threading import RLock
import cv2
import numpy as np
import torch
import rospy
from cv_bridge import CvBridge
from dataproc.io import append_to_csv, write_to_csv
from dataproc.imgproc import ego_to_cam, get_only_in_img_mask
from dataproc.transformations import transform_cloud
from dataproc.ros import write_intrinsics_to_yaml, append_tf_to_yaml
from sensor_msgs.msg import CompressedImage, PointCloud2, CameraInfo
from time import time
from message_filters import ApproximateTimeSynchronizer, Subscriber
import tf2_ros
from ros_numpy import numpify
import matplotlib.pyplot as plt
import matplotlib as mpl


class DataProc:
    def __init__(self,
                 img_topics=[],
                 camera_info_topics=[],
                 lidar_topic='/points',
                 robot_frame='base_link',
                 map_frame='map',
                 max_msgs_delay=0.5,
                 output_path='',
                 save_time_period=1.0,
                 ):
        self.map_frame = map_frame
        self.robot_frame = robot_frame
        self.lidar_frame = None
        self.camera_frames = []
        self.img_topics = np.sort(img_topics).tolist()
        self.camera_info_topics = np.sort(camera_info_topics).tolist()
        self.lidar_topic = lidar_topic
        self.cv_bridge = CvBridge()
        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer)
        self.proc_lock = RLock()
        self.max_msgs_delay = max_msgs_delay
        self.output_path = output_path
        self.rate = rospy.Rate(1.0 / save_time_period)

    def start(self):
        """
        Subscribing to images, camera info and points with approximate time synchronization
        """
        self.subs = []
        for topic in self.img_topics:
            rospy.loginfo('Subscribing to %s' % topic)
            self.subs.append(Subscriber(topic, CompressedImage))
        for topic in self.camera_info_topics:
            rospy.loginfo('Subscribing to %s' % topic)
            self.subs.append(Subscriber(topic, CameraInfo))
        rospy.loginfo('Subscribing to %s' % self.lidar_topic)
        self.subs.append(Subscriber(self.lidar_topic, PointCloud2))
        self.sync = ApproximateTimeSynchronizer(self.subs, queue_size=10, slop=self.max_msgs_delay)
        self.sync.registerCallback(self.callback)

    def get_cam_calib_from_info_msg(self, msg):
        """
        Get camera calibration parameters from CameraInfo message.
        :param msg: CameraInfo message
        :return: E - extrinsics (4x4),
                 K - intrinsics (3x3),
                 D - distortion coefficients (5,)
        """
        assert isinstance(msg, CameraInfo)

        time = rospy.Time(0)
        timeout = rospy.Duration.from_sec(1.0)
        try:
            tf = self.tf_buffer.lookup_transform(self.robot_frame, msg.header.frame_id, time, timeout)
        except Exception as ex:
            rospy.logerr('Could not transform from camera %s to robot %s: %s.',
                         msg.header.frame_id, self.robot_frame, ex)
            raise ex

        E = np.array(numpify(tf.transform), dtype=np.float32).reshape((4, 4))
        K = np.array(msg.K, dtype=np.float32).reshape((3, 3))
        D = np.array(msg.D, dtype=np.float32)

        return E, K, D

    def get_sensor_data(self, img_msgs, info_msgs, lidar_msg):
        """
        Get inputs for LSS model from image and camera info messages.
        """
        assert len(img_msgs) == len(info_msgs)
        assert isinstance(img_msgs[0], CompressedImage)
        assert isinstance(info_msgs[0], CameraInfo)
        assert isinstance(lidar_msg, PointCloud2)
        imgs = []
        Ks = []
        Es = []
        stamp = img_msgs[0].header.stamp
        for cam_i, (img_msg, info_msg) in enumerate(zip(img_msgs, info_msgs)):
            img = self.cv_bridge.compressed_imgmsg_to_cv2(img_msg)
            E, K, D = self.get_cam_calib_from_info_msg(info_msg)
            imgs.append(img)
            Ks.append(K)
            Es.append(E)

            if len(self.camera_frames) < len(self.img_topics):
                self.camera_frames.append(info_msg.header.frame_id)
                # self.camera_frames.append(self.img_topics[cam_i].split('/')[0])

        imgs = np.stack(imgs)
        Ks = np.stack(Ks)
        Es = np.stack(Es)

        if self.lidar_frame is None:
            self.lidar_frame = lidar_msg.header.frame_id
        lidar_cloud = numpify(lidar_msg)
        if lidar_cloud.ndim > 1:
            lidar_cloud = lidar_cloud.reshape(-1,)

        return imgs, Ks, Es, lidar_cloud, stamp

    def get_map_pose(self, frame, stamp=None):
        if stamp is None:
            stamp = rospy.Time(0)
        try:
            tf = self.tf_buffer.lookup_transform(self.map_frame, frame, stamp, rospy.Duration(1.0))
        except Exception as ex:
            rospy.logerr('Could not transform from %s to %s: %s.', frame, self.map_frame, ex)
            return None
        pose = np.array(numpify(tf.transform), dtype=np.float32).reshape((4, 4))
        return pose

    def callback(self, *msgs):
        with self.proc_lock:
            rospy.logdebug('Received %d messages' % len(msgs))
            stamps = [msg.header.stamp.to_sec() for msg in msgs]
            max_delay = max(stamps) - min(stamps)
            rospy.logdebug('Max delay: %.3f [sec]' % max_delay)
            t0 = time()
            self.proc(*msgs)
            rospy.logdebug('Processing time: %.3f [sec]' % (time() - t0))
            self.rate.sleep()

    def draw_points_in_images(self, imgs, Ks, Es, points, output_file='points.png'):
        try:
            stamp = rospy.Time(0)
            timeout = rospy.Duration.from_sec(1.0)
            tf = self.tf_buffer.lookup_transform(self.robot_frame, self.lidar_frame, stamp, timeout)
        except Exception as ex:
            rospy.logerr('Could not transform from camera %s to robot %s: %s.',
                         self.lidar_frame, self.robot_frame, ex)
            raise ex
        Tr = np.array(numpify(tf.transform), dtype=np.float32).reshape((4, 4))
        points = transform_cloud(points, Tr)

        imgs = torch.from_numpy(imgs)
        Ks = torch.from_numpy(Ks)
        Es = torch.from_numpy(Es)
        points = torch.from_numpy(points).T

        Rs = Es[:, :3, :3]
        ts = Es[:, :3, 3]

        assert len(imgs) % 2 == 0, 'Number of images must be even'
        n_rows, n_cols = 2, len(imgs) // 2
        fig = plt.figure(figsize=(n_cols * 5, n_rows * 5))
        gs = mpl.gridspec.GridSpec(n_rows, n_cols)
        gs.update(wspace=0.0, hspace=0.0, left=0.0, right=1.0, top=1.0, bottom=0.0)
        H, W = imgs.shape[1], imgs.shape[2]
        for imgi in range(len(imgs)):
            ego_pts = ego_to_cam(points, Rs[imgi], ts[imgi], Ks[imgi])
            mask = get_only_in_img_mask(ego_pts, H, W)
            ax = plt.subplot(gs[imgi // n_cols, imgi % n_cols])
            ax.imshow(imgs[imgi].numpy()[..., ::-1])
            plt.scatter(ego_pts[0, mask], ego_pts[1, mask], c=points[2, mask],
                        s=1, alpha=0.2, cmap='jet', vmin=-1, vmax=1)
            plt.axis('off')
        plt.savefig(output_file)
        plt.close(fig)

    def save_data(self, imgs, info_msgs, lidar_cloud, map_pose, stamp):
        assert len(imgs) == len(info_msgs)
        assert imgs.shape[0] == len(self.img_topics)
        assert isinstance(map_pose, np.ndarray) and map_pose.shape == (4, 4)

        cloud_path = os.path.join(self.output_path, 'clouds')
        img_path = os.path.join(self.output_path, 'images')
        poses_path = os.path.join(self.output_path, 'poses')
        poses_csv = os.path.join(poses_path, 'lidar_poses.csv')
        calib_path = os.path.join(self.output_path, 'calibration')

        if not os.path.exists(calib_path):
            intrinsics_path = os.path.join(calib_path, 'cameras')
            os.makedirs(intrinsics_path)
            for i, info_msg in enumerate(info_msgs):
                camera = self.img_topics[i].split('/')[1]
                write_intrinsics_to_yaml(intrinsics_path, info_msg, camera_name=camera)

            tf_path = os.path.join(calib_path, 'transformations.yaml')
            assert self.lidar_frame is not None
            append_tf_to_yaml(tf_path, self.robot_frame, self.lidar_frame, tf_buffer=self.tf_buffer, stamp=stamp,
                              matrix_name=f'T_{self.robot_frame}__os_sensor')

            assert len(self.camera_frames) == len(self.img_topics)
            for i, camera_frame in enumerate(self.camera_frames):
                append_tf_to_yaml(tf_path, self.robot_frame, camera_frame, tf_buffer=self.tf_buffer, stamp=stamp,
                                  matrix_name=f'T_{self.robot_frame}__{self.img_topics[i].split("/")[1]}')

            # append robot_frame -> base_footprint
            append_tf_to_yaml(tf_path, self.robot_frame, 'base_footprint', tf_buffer=self.tf_buffer, stamp=stamp,
                              matrix_name=f'T_{self.robot_frame}__base_footprint')

        t = stamp.to_sec()
        id = str('%.9f' % t).replace('.', '_')
        camera_names = [c.split('/')[1] for c in self.img_topics]

        # save lidar point cloud
        if not os.path.exists(cloud_path):
            os.makedirs(cloud_path)
        np.savez(os.path.join(cloud_path, id + '.npz'), cloud=lidar_cloud)

        # save images
        if not os.path.exists(img_path):
            os.makedirs(img_path)
        for i, img in enumerate(imgs):
            cv2.imwrite(os.path.join(img_path, id + '_%s.png' % camera_names[i]), img)

        # save poses to csv
        if not os.path.exists(poses_csv):
            write_to_csv(poses_csv, 'stamp, T00, T01, T02, T03, T10, T11, T12, T13, T20, T21, T22, T23\n')
        append_to_csv(poses_csv, '%.9f, %s\n' % (t, ', '.join(['%.3f' % x for x in map_pose[:3, :].flatten()])))

    def proc(self, *msgs):
        n = len(msgs)
        assert n % 2 == 1, 'Number of messages must be odd'
        assert n >= 3, 'At least 3 messages are required: 1 image, 1 camera info, 1 lidar'
        n_cams = (n - 1) // 2
        for i in range(n_cams):
            assert isinstance(msgs[i], CompressedImage), 'First %d messages must be CompressedImage' % n_cams
        for i in range(n_cams, 2*n_cams):
            assert isinstance(msgs[i], CameraInfo), 'Next %d messages must be CameraInfo' % n_cams
        img_msgs = msgs[:n_cams]
        info_msgs = msgs[n_cams : 2*n_cams]
        lidar_msg = msgs[-1]
        assert isinstance(lidar_msg, PointCloud2), 'Last message must be PointCloud2'

        imgs, Ks, Es, lidar_cloud, stamp = self.get_sensor_data(img_msgs, info_msgs, lidar_msg)
        rospy.logdebug('imgs shape: %s' % str(imgs.shape))
        rospy.logdebug('Ks shape: %s' % str(Ks.shape))
        rospy.logdebug('Es shape: %s' % str(Es.shape))
        rospy.logdebug('lidar cloud shape: %s' % str(lidar_cloud.shape))

        # self.draw_points_in_images(imgs, Ks, Es, position(lidar_cloud))
        lidar_pose = self.get_map_pose(frame=self.lidar_frame, stamp=stamp)

        # save data
        if lidar_pose is None:
            return
        rospy.loginfo('Saving data sample to %s' % self.output_path)
        self.save_data(imgs, info_msgs, lidar_cloud, lidar_pose, stamp)

    def spin(self):
        try:
            rospy.spin()
        except rospy.ROSInterruptException:
            pass


def main():
    rospy.init_node('dataproc', anonymous=True, log_level=rospy.DEBUG)

    img_topics = rospy.get_param('~img_topics', [])
    camera_info_topics = rospy.get_param('~camera_info_topics', [])
    lidar_topic = rospy.get_param('~lidar_topic', '/points')
    robot_frame = rospy.get_param('~robot_frame', 'base_link')
    max_msgs_delay = rospy.get_param('~max_msgs_delay', 0.1)
    output_path = rospy.get_param('~output_path', '')
    save_time_period = rospy.get_param('~save_time_period', 1.0)

    node = DataProc(img_topics=img_topics, camera_info_topics=camera_info_topics,
                    lidar_topic=lidar_topic,
                    robot_frame=robot_frame, max_msgs_delay=max_msgs_delay,
                    output_path=output_path, save_time_period=save_time_period)
    node.start()
    node.spin()


if __name__ == '__main__':
    main()
