#!/usr/bin/env python

import numpy as np
from skimage.draw import polygon
import rospy
from monoforce.ros import gridmap_msg_to_numpy, height_map_to_gridmap_msg
from grid_map_msgs.msg import GridMap


class GridMapMasker:
    def __init__(self,
                 gridmap_topic='/grid_map/terrain',
                 ):
        # height map mask
        self.mask = self.front_height_map_mask()

        # height map publisher
        self.gridmap_pub = rospy.Publisher('/grid_map/terrain_masked', GridMap, queue_size=1)

        # height map subscriber
        self.gridmap_sub = rospy.Subscriber(gridmap_topic, GridMap, self.gridmap_callback)

    def front_height_map_mask(self):
        K = [1461.57941, 0.0, 1028.16795, 0.0, 1461.83192, 820.47617, 0.0, 0.0, 1.0]
        K = np.asarray(K, dtype=np.float32).reshape(3, 3)

        # get fov from camera intrinsics
        img_h, img_w = 1542, 2056
        fx, fy = K[0, 0], K[1, 1]

        # fov_x = 2 * np.arctan2(img_h, 2 * fx)
        fov_y = 2 * np.arctan2(img_w, 2 * fy)

        # camera frustum mask
        d = 6.4
        res = 0.1
        h, w = 2 * d / res, 2 * d / res
        h, w = int(h), int(w)
        mask = np.zeros((h, w), dtype=np.float32)

        to_grid = lambda x: np.array([x[1], x[0]]) / res + np.array([h // 2, w // 2])
        A = to_grid([0, 0])
        B = to_grid([d * np.tan(fov_y / 2), d])
        C = to_grid([-d * np.tan(fov_y / 2), d])

        # select triangle
        rr, cc = polygon([A[0], B[0], C[0]], [A[1], B[1], C[1]], mask.shape)
        mask[rr, cc] = 1

        return np.asarray(mask, dtype=bool)

    def gridmap_callback(self, msg):
        assert isinstance(msg, GridMap)

        # convert grid map to height map
        height = gridmap_msg_to_numpy(msg, 'elevation')
        assert not np.all(np.isnan(height))
        assert np.all(np.isfinite(height))
        assert height.ndim == 2, 'Height map must be 2D'
        rospy.loginfo('Received grid map of shape: %s' % str(height.shape))

        # convert height map to grid map
        gridmap_msg = height_map_to_gridmap_msg(height, grid_res=0.1, mask=self.mask)
        gridmap_msg.info = msg.info

        # publish masked grid map
        self.gridmap_pub.publish(gridmap_msg)
        rospy.loginfo('Published masked grid map of shape: %s' % str(height.shape))


    @staticmethod
    def spin():
        try:
            rospy.spin()
        except rospy.ROSInterruptException:
            pass


def main():
    rospy.init_node('gridmap_masker', anonymous=True, log_level=rospy.DEBUG)

    gridmap_topic = rospy.get_param('~gridmap_topic')

    node = GridMapMasker(gridmap_topic=gridmap_topic)
    node.spin()


if __name__ == '__main__':
    main()
