#!/usr/bin/env python

import sys
sys.path.append('../src')
import os
from rosbag import Bag, ROSBagException, Compression
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv
from tf2_ros import BufferCore, TransformException
from ros_numpy import numpify, msgify
import rospy


def load_buffer(bag_paths):
    tf_topics = ['/tf', '/tf_static']
    # buffer = BufferCore(cache_time=rospy.Duration(2**31 - 1))
    # buffer = BufferCore(cache_time=rospy.Duration(24 * 60 * 60))
    buffer = BufferCore(rospy.Duration(24 * 60 * 60))
    for path in bag_paths:
        try:
            with Bag(path, 'r') as bag:
                for topic, msg, stamp in tqdm(bag.read_messages(topics=tf_topics),
                                              desc='%s: reading transforms' % path.split('/')[-1],
                                              total=bag.get_message_count(topic_filters=tf_topics)):
                    if topic == '/tf':
                        for tf in msg.transforms:
                            buffer.set_transform(tf, 'bag')
                    elif topic == '/tf_static':
                        for tf in msg.transforms:
                            buffer.set_transform_static(tf, 'bag')
        except ROSBagException as ex:
            print('Could not read %s: %s' % (path, ex))

    return buffer

def get_pose(buffer, msg, fixed_frame):
    # Find transform from input cloud to fixed frame.
    try:
        input_to_fixed = buffer.lookup_transform_core(fixed_frame, msg.header.frame_id, msg.header.stamp)
    except TransformException as ex:
        print('Could not transform from %s to %s at %.3f s.' % (
               msg.header.frame_id, fixed_frame, msg.header.stamp.to_sec()))
        return None
    input_to_fixed = numpify(input_to_fixed.transform)
    return input_to_fixed

def process_bag(bag_path, poses_path, lidar_topic, fixed_frame='map'):
    write_to_csv(poses_path, 'stamp, T00, T01, T02, T03, T10, T11, T12, T13, T20, T21, T22, T23\n')
    buffer = load_buffer([bag_path])

    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[lidar_topic]),
                                      total=bag.get_message_count(lidar_topic)):
            lidar_pose = get_pose(buffer, msg, fixed_frame)
            t = stamp.to_sec()
            if lidar_pose is not None:
                append_to_csv(poses_path, '%.9f, %s\n' % (t, ', '.join(['%.3f' % x for x in lidar_pose[:3, :].flatten()])))


def main():
    dir_path = '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/25-03-19-petrin/'
    bag_paths = [os.path.join(dir_path, f) for f in os.listdir(dir_path) if f.endswith('.bag')]
    print(bag_paths)

    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path), f'Path {bag_path} does not exist'
        data_path = os.path.basename(bag_path.replace('.bag', ''))
        data_path = os.path.join('/media/ruslan/VRAS-DATA 4TB 2/datasets/ROUGH/', data_path)
        poses_path = os.path.join(data_path, 'poses', 'lidar_poses.csv')
        print(f'Writing lidar poses to {poses_path}')
        lidar_topic = '/points_filtered_kontron'
        if os.path.exists(poses_path):
            print(f'File {poses_path} already exists, skipping')
            continue
        process_bag(bag_path, poses_path, lidar_topic)
    print('Done')


if __name__ == '__main__':
    main()
