#!/usr/bin/env python

import os
from rosbag import Bag
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv
from monoforce.datasets import robingas_seq_paths


def process_bag(bag_path, controls_topic, controls_path):
    write_to_csv(controls_path, 'stamp [sec], left_track_vel [m/sec], right_track_vel [m/sec]\n')
    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[controls_topic]),
                                      total=bag.get_message_count(controls_topic)):
            left_track_vel = msg.left
            right_track_vel = msg.right
            stamp = stamp.to_sec()
            print(stamp, left_track_vel, right_track_vel)
            append_to_csv(controls_path, f'{stamp}, {left_track_vel}, {right_track_vel}\n')
        bag.close()


def main():
    bag_paths = [
        # '/media/ruslan/SSD/data/bags/robingas/data/22-10-20-unhost/ugv_2022-10-20-14-30-57.bag',
        # '/media/ruslan/SSD/data/bags/robingas/data/22-10-20-unhost/ugv_2022-10-20-14-05-42.bag',
        '/media/ruslan/SSD/data/bags/robingas/data/22-10-20-unhost/ugv_2022-10-20-13-58-22.bag',
    ]
    controls_topic = '/tracks_vel'
    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path)
        lidar_clouds_path = os.path.join(robingas_seq_paths['tradr'][path_i], 'clouds/')
        controls_path = os.path.join(lidar_clouds_path.replace('/clouds', '/controls'), 'tracks_vel.csv')

        process_bag(bag_path, controls_topic, controls_path)
    print('Done')


if __name__ == '__main__':
    main()
