#!/usr/bin/env python

import os
from rosbag import Bag
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv


def process_bag(bag_path, controls_topic, controls_path):
    write_to_csv(controls_path, 'stamp [sec], left_track_vel [m/sec], right_track_vel [m/sec]\n')
    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[controls_topic]),
                                      total=bag.get_message_count(controls_topic)):
            left_track_vel = msg.left
            right_track_vel = msg.right
            stamp = stamp.to_sec()
            # print(stamp, left_track_vel, right_track_vel)
            append_to_csv(controls_path, f'{stamp}, {left_track_vel}, {right_track_vel}\n')
        bag.close()


def main():
    bag_paths = [
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset_24-09-26/ugv_2024-09-26-13-54-18.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset_24-09-26/ugv_2024-09-26-13-58-46.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset_24-09-26/ugv_2024-09-26-14-03-57.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset_24-09-26/ugv_2024-09-26-14-14-42.bag',
    ]
    controls_topic = '/tracks_vel'
    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path)
        data_path = bag_path.replace('.bag', '')
        print(f'Processing {bag_path}...')
        controls_path = os.path.join(data_path, 'controls', 'tracks_vel.csv')
        print('Saving to:', controls_path)
        process_bag(bag_path, controls_topic, controls_path)
    print('Done')


if __name__ == '__main__':
    main()
