#!/usr/bin/env python

import sys
sys.path.append('../src')
import os
from rosbag import Bag
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv


def process_bag(bag_path, controls_topic, controls_path):
    print("Writing to", controls_path)
    write_to_csv(controls_path, 'stamp, linear_vel [m/sec], angular_vel [rad/sec]\n')
    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[controls_topic]),
                                      total=bag.get_message_count(controls_topic)):
            v = msg.linear.x
            w = msg.angular.z
            stamp = stamp.to_sec()
            # print(stamp, v, w)
            append_to_csv(controls_path, f'{stamp}, {v}, {w}\n')
        bag.close()


def main():
    bag_paths = [
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-08-initial_tests_marv/24-08-14-monoforce-long_drive.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/marv_2024-09-26-13-46-51.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/marv_2024-09-26-13-54-43.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-12-34-53.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-13-01-40.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-13-17-08.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-13-29-39.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-13-43-21.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-13-57-57.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-14-12-29.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-14-22-10.bag',
        # '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/marv_2024-10-05-14-28-15.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-16-42.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-26-47.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-35-05.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-52-07.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-56-33.bag',

        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-10-petrin-clone/ugv_2024-09-10-17-02-31.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-10-petrin-clone/ugv_2024-09-10-17-12-12.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/ugv_2024-09-26-13-54-18.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/ugv_2024-09-26-13-58-46.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/ugv_2024-09-26-14-03-57.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/ugv_2024-09-26-14-27-16.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-09-26-petrin-marv_clone/ugv_2024-09-26-14-14-42.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/ugv_2024-10-05-15-40-41.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/ugv_2024-10-05-15-48-31.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/ugv_2024-10-05-15-58-52.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/ugv_2024-10-05-16-08-30.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-05-pokor-petrin/ugv_2024-10-05-16-24-48.bag',
    ]
    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path), f'Path {bag_path} does not exist'
        data_path = os.path.basename(bag_path.replace('.bag', ''))
        data_path = os.path.join('/media/ruslan/VRAS-DATA 4TB 2/datasets/ROUGH-v2/', data_path)
        print(f'Writing controls to {data_path}')
        controls_path = os.path.join(data_path, 'controls', 'cmd_vel.csv')
        if os.path.exists(controls_path):
            print(f'File {controls_path} already exists, skipping')
            continue

        controls_topic = '/cmd_vel' if 'ugv' in bag_path else '/marv/cartesian_controller/cmd_vel'
        process_bag(bag_path, controls_topic, controls_path)
    print('Done')


if __name__ == '__main__':
    main()
