#!/usr/bin/env python

import os
from rosbag import Bag
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv


def process_bag(bag_path, controls_topic, controls_path):
    print("Writing to", controls_path)
    write_to_csv(controls_path, 'stamp, front_left_flipper_wheel [m/sec], front_right_flipper_wheel [m/sec], rear_left_flipper_wheel [m/sec], rear_right_flipper_wheel [m/sec]\n')
    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[controls_topic]),
                                      total=bag.get_message_count(controls_topic)):
            vels = msg.velocity  # front_left_flipper_wheel, front_right_flipper_wheel, rear_left_flipper_wheel, rear_right_flipper_wheel
            stamp = stamp.to_sec()
            # print(stamp, vels)
            append_to_csv(controls_path, f'{stamp}, {vels[0]}, {vels[1]}, {vels[2]}, {vels[3]}\n')
        bag.close()


def main():
    bag_paths = [
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-16-42.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-26-47.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-35-05.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-52-07.bag',
        '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/24-10-31-petrin/marv_2024-10-31-15-56-33.bag',
    ]
    controls_topic = '/marv/tracks/joint_states'
    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path)
        data_path = bag_path.replace('.bag', '')
        print(f'Processing {bag_path}...')
        controls_path = os.path.join(data_path, 'controls', 'tracks_vel.csv')

        process_bag(bag_path, controls_topic, controls_path)
    print('Done')


if __name__ == '__main__':
    main()
