#!/usr/bin/env python

import sys
sys.path.append('../src')
import os
from rosbag import Bag
from tqdm import tqdm
from dataproc.io import write_to_csv, append_to_csv


def process_bag(bag_path, controls_topic, controls_path):
    print("Writing to", controls_path)
    write_to_csv(controls_path, 'stamp, linear_vel [m/sec], angular_vel [rad/sec]\n')
    with Bag(bag_path) as bag:
        for topic, msg, stamp in tqdm(bag.read_messages(topics=[controls_topic]),
                                      total=bag.get_message_count(controls_topic)):
            v = msg.linear.x
            w = msg.angular.z
            stamp = stamp.to_sec()
            # print(stamp, v, w)
            append_to_csv(controls_path, f'{stamp}, {v}, {w}\n')
        bag.close()


def main():
    dir_path = '/media/ruslan/VRAS-DATA 4TB 2/outdoor_dataset/25-03-19-petrin/'
    bag_paths = [os.path.join(dir_path, f) for f in os.listdir(dir_path) if f.endswith('.bag')]
    print(bag_paths)
    for path_i, bag_path in enumerate(bag_paths):
        assert os.path.exists(bag_path), f'Path {bag_path} does not exist'
        data_path = os.path.basename(bag_path.replace('.bag', ''))
        data_path = os.path.join('/media/ruslan/VRAS-DATA 4TB 2/datasets/ROUGH/', data_path)
        print(f'Writing controls to {data_path}')
        controls_path = os.path.join(data_path, 'controls', 'cmd_vel.csv')
        if os.path.exists(controls_path):
            print(f'File {controls_path} already exists, skipping')
            continue

        controls_topic = '/cmd_vel' if 'ugv' in bag_path else '/marv/cartesian_controller/cmd_vel'
        process_bag(bag_path, controls_topic, controls_path)
    print('Done')


if __name__ == '__main__':
    main()
