#! /usr/bin/env python

from mmseg.apis import init_model, inference_model, show_result_pyplot
import os
from monoforce.datasets.rough import rough_seq_paths
from PIL import Image
import numpy as np
from tqdm import tqdm


config_path = '../packages/WildScenes/wildscenes/configs/deeplabv3/deeplabv3_r50-d8_2xb20-80k_wildscenes-512x512_standard.py'
checkpoint_path = '../packages/WildScenes/pretrained_models/deeplabv3_wildscenes.pth'
model = init_model(config_path, checkpoint_path)

for seq_path in tqdm(rough_seq_paths):
    print(f'Processing {seq_path}')
    img_folder = os.path.join(seq_path, 'images')
    seg_folder = os.path.join(img_folder, 'wildscenes_seg/seg')
    vis_folder = os.path.join(img_folder, 'wildscenes_seg/vis')
    os.makedirs(seg_folder, exist_ok=True)
    os.makedirs(vis_folder, exist_ok=True)
    img_paths = sorted([os.path.join(img_folder, img) for img in os.listdir(img_folder) if img.endswith('.png')])
    for img_path in tqdm(img_paths):
        seg_path = os.path.join(seg_folder, os.path.basename(img_path))
        vis_path = os.path.join(vis_folder, os.path.basename(img_path))
        if os.path.exists(seg_path) and os.path.exists(vis_path):
            continue
        # inference
        result = inference_model(model, img_path)
        seg = np.asarray(result.pred_sem_seg.data.cpu().numpy().squeeze(0), dtype=np.uint8)
        vis = show_result_pyplot(model, img_path, result, show=False)
        # save segmentation
        Image.fromarray(seg).save(seg_path)
        Image.fromarray(vis).save(vis_path)
print('done!')