#! /usr/bin/env python

from mmseg.apis import init_model, inference_model, show_result_pyplot
import os
from monoforce.datasets.rough import rough_seq_paths
from monoforce.models.terrain_encoder.utils import resize_img
from PIL import Image
import numpy as np
from tqdm import tqdm


def main():
    config_path = '../packages/WildScenes/wildscenes/configs/deeplabv3/deeplabv3_r50-d8_2xb20-80k_wildscenes-512x512_standard.py'
    checkpoint_path = '../packages/WildScenes/pretrained_models/deeplabv3_wildscenes.pth'
    model = init_model(config_path, checkpoint_path)
    # paths = rough_seq_paths
    paths = sorted([os.path.join('../data/ROUGH/', f) for f in os.listdir('../data/ROUGH/') if f.startswith('marv_2025-03-19-')])
    # print(paths)

    for seq_path in tqdm(paths):
        print(f'Processing {seq_path}')
        img_folder = os.path.join(seq_path, 'images')
        seg_folder = os.path.join(img_folder, 'wildscenes_seg/seg')
        vis_folder = os.path.join(img_folder, 'wildscenes_seg/vis')
        os.makedirs(seg_folder, exist_ok=True)
        os.makedirs(vis_folder, exist_ok=True)
        img_paths = sorted([os.path.join(img_folder, img) for img in os.listdir(img_folder) if img.endswith('.png')])
        for img_path in tqdm(img_paths):
            seg_path = os.path.join(seg_folder, os.path.basename(img_path))
            vis_path = os.path.join(vis_folder, os.path.basename(img_path))
            if os.path.exists(seg_path) and os.path.exists(vis_path):
                continue
            # inference
            img = resize_img(Image.open(img_path))
            img_path_resized = os.path.join(img_folder, 'resized', os.path.basename(img_path))
            os.makedirs(os.path.dirname(img_path_resized), exist_ok=True)
            img.save(img_path_resized)
            result = inference_model(model, img_path_resized)
            seg = np.asarray(result.pred_sem_seg.data.cpu().numpy().squeeze(0), dtype=np.uint8)
            vis = show_result_pyplot(model, img_path_resized, result, show=False)
            # save segmentation
            Image.fromarray(seg).save(seg_path)
            Image.fromarray(vis).save(vis_path)
    print('done!')


if __name__ == '__main__':
    main()