#!/usr/bin/env python

import os
import numpy as np
from monoforce.dphys_config import DPhysConfig
from monoforce.datasets import rough_seq_paths, ROUGH
from monoforce.utils import explore_data
from monoforce.utils import read_yaml

import matplotlib as mpl
try:
    mpl.use('TkAgg')
except:
    try:
        mpl.use('QtAgg')
    except:
        print('Cannot set matplotlib backend')
    pass

def vis_data(dataset, robot='husky'):
    if robot in ['husky_oru', 'tradr']:
        lss_config_path = f'../../monoforce/monoforce/config/lss_cfg_{robot}.yaml'
    else:
        lss_config_path = '../../monoforce/monoforce/config/lss_cfg.yaml'

    for path in rough_seq_paths:
        assert os.path.isdir(path), 'Data path %s does not exist' % path
        lss_config = read_yaml(lss_config_path)
        dphys_cfg = DPhysConfig(robot=robot)
        ds = ROUGH(path, is_train=False, lss_cfg=lss_config, dphys_cfg=dphys_cfg)
        ds = ds[np.random.choice(len(ds), 32, replace=False)]
        explore_data(ds, sample_range='random', save=False)


def visualize():
    datasets = ['rough']
    robots = ['marv']
    for dataset in datasets:
        for robot in robots:
            vis_data(dataset, robot)
            if dataset == 'rellis3d':
                print('Rellis3D does not have multiple robots')
                break

def main():
    visualize()


if __name__ == '__main__':
    main()
